# Uncomment the next line to define a global platform for your project
# platform :ios, '13'

target 'UsersApp' do
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.4.4'
  pod 'Kingfisher', '~> 6.3.1'
end

target 'UsersAppTests' do
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.4.4'
  pod 'Kingfisher', '~> 6.3.1'
end